spring:
  r2dbc:
    url: r2dbc:h2:mem:///intershopdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:

  thymeleaf:
    encoding: UTF-8
    mode: HTML
    servlet:
      content-type: text/html

  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql

  main:
    web-application-type: reactive

server:
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: always